---
- name: Play 1
  hosts: tom@worker
  become: true
  tasks:
    - name: apt update
      command: sudo apt update

    - name: Get Minikube info
      command: wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
      
    - name: change permissions for minikube  
      command: chmod +x minikube-linux-amd64
      
    - name: move minikube into local/bin/minikube
      command: sudo mv minikube-linux-amd64 /usr/local/bin/minikube 
    
    - name: Installing Prerequisites for Kubernetes
      apt: 
        name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
        state: present
    
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
        mode: 0600
    
    - name: Install Docker Engine.
      apt: 
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

- name: Play 2
  hosts: worker
  become_user: tom
  tasks: 
    - name: Copy kubernetes YAML
      ansible.builtin.copy:
        src: 2020-DevOps-Case-Study-1/kubernetes.yml
        dest: /etc/kubernetes.yml
        owner: tom
        mode: 7777
    
    - name: Apply kubernetes YAML
      command: kubetcl create -f /App/kubernetes.yml


