---
- name: Play 1
  hosts: tom@worker
  become: yes
  tasks:
    - name: apt update
      command: apt update

    - name: do more
      command: wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64